groups:
  - name: ANFLAlerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          description: Error rate above 5% for 5 minutes

      - alert: VaultUnhealthy
        expr: vault_up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Vault is unhealthy
          description: Vault health check failed

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage
          description: Memory usage is above 85%

      - alert: APILatencyHigh
        expr: http_request_duration_seconds{quantile="0.9"} > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High API latency
          description: 90th percentile latency is above 2 seconds

      - alert: ModelPredictionErrors
        expr: rate(model_prediction_errors_total[5m]) > 0.01
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High model prediction error rate
          description: Model prediction error rate is above 1%