# ANFL Framework Prometheus Configuration
# Generated: 2025-02-08

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'anfl-infrastructure'
    static_configs:
      - targets: ['localhost:9090']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: go_.*
        action: drop

  - job_name: 'vault'
    metrics_path: '/v1/sys/metrics'
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['localhost:8200']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

rule_files:
  - /etc/prometheus/rules/*.yml

storage:
  tsdb:
    retention.time: 15d
    retention.size: 50GB