# ----------------------------------------------------------------------------
# File: networkpolicy.yaml
# Location: /Volumes/mattstack/VSCode/AeonNovaFutureLabs/helm/ai-components/templates/
#
# Purpose: Network policy for AI components
# Security Level: Confidential
# Owner: Infrastructure Team
# Version: 1.0
# Last Modified: 2025-02-08
# ----------------------------------------------------------------------------

{{- if .Values.security.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ai-components.fullname" . }}-network-policy
  labels:
    {{- include "ai-components.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ai-components.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- with .Values.security.networkPolicy.ingressRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    - ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
        {{- if .Values.monitoring.prometheus.serviceMonitor.enabled }}
        - protocol: TCP
          port: {{ .Values.service.metricsPort }}
        {{- end }}
  egress:
    {{- with .Values.security.networkPolicy.egressRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow vector store access
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: vector-store
      ports:
        - protocol: TCP
          port: 6379
    # Allow monitoring system access
    {{- if .Values.monitoring.enabled }}
    - to:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: {{ .Values.service.metricsPort }}
    {{- end }}
{{- end }}