# ANFL Framework Grafana Configuration
# Generated: 2025-02-08

server:
  http_port: ${ANFL_GRAFANA_PORT}
  domain: ${ANFL_GRAFANA_DOMAIN}
  root_url: ${ANFL_GRAFANA_ROOT_URL}

security:
  admin_user: ${ANFL_GRAFANA_ADMIN_USER}
  admin_password: ${ANFL_GRAFANA_ADMIN_PASSWORD}
  secret_key: ${ANFL_GRAFANA_SECRET_KEY}
  disable_gravatar: true
  cookie_secure: true
  cookie_samesite: strict
  allow_embedding: false

auth:
  disable_login_form: false
  disable_signout_menu: false
  oauth_auto_login: false

users:
  allow_sign_up: false
  auto_assign_org: true
  auto_assign_org_role: Editor

auth.generic_oauth:
  enabled: true
  name: Vault
  client_id: ${ANFL_VAULT_OAUTH_CLIENT_ID}
  client_secret: ${ANFL_VAULT_OAUTH_CLIENT_SECRET}
  scopes: openid profile email
  auth_url: ${ANFL_VAULT_ADDR}/v1/identity/oidc/provider/anfl/authorize
  token_url: ${ANFL_VAULT_ADDR}/v1/identity/oidc/provider/anfl/token
  api_url: ${ANFL_VAULT_ADDR}/v1/identity/oidc/provider/anfl/userinfo
  allowed_domains: []
  allow_sign_up: true

dashboards:
  default_home_dashboard_path: /var/lib/grafana/dashboards/overview.json

analytics:
  reporting_enabled: false
  check_for_updates: false

log:
  mode: console file
  level: info

paths:
  data: /var/lib/grafana
  logs: /var/log/grafana
  plugins: /var/lib/grafana/plugins
  provisioning: /etc/grafana/provisioning

unified_alerting:
  enabled: true

feature_toggles:
  enable: true