# ----------------------------------------------------------------------------
# File: ai-components.yaml
# Location: /Volumes/mattstack/VSCode/AeonNovaFutureLabs/k8s/base/
#
# Purpose: Base Kubernetes configuration for AI components
# Security Level: Confidential
# Owner: Infrastructure Team
# Version: 1.0
# Last Modified: 2025-02-08
# ----------------------------------------------------------------------------

apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-components-config
data:
  VECTOR_STORE_HOST: "vector-store-service"
  VECTOR_STORE_PORT: "6379"
  LOG_LEVEL: "INFO"
  METRICS_PORT: "9090"
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-components-secrets
type: Opaque
data:
  OPENWEATHER_API_KEY: "" # Base64 encoded
  SNYK_TOKEN: "" # Base64 encoded
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-components
  labels:
    app: ai-components
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-components
  template:
    metadata:
      labels:
        app: ai-components
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: ai-components
        image: ghcr.io/aeonnovafuturelabs/ai:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: VECTOR_STORE_HOST
          valueFrom:
            configMapKeyRef:
              name: ai-components-config
              key: VECTOR_STORE_HOST
        - name: VECTOR_STORE_PORT
          valueFrom:
            configMapKeyRef:
              name: ai-components-config
              key: VECTOR_STORE_PORT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: ai-components-config
              key: LOG_LEVEL
        - name: METRICS_PORT
          valueFrom:
            configMapKeyRef:
              name: ai-components-config
              key: METRICS_PORT
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-components-secrets
              key: OPENWEATHER_API_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 15
          periodSeconds: 15
        volumeMounts:
        - name: data
          mountPath: /app/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ai-components-data
---
apiVersion: v1
kind: Service
metadata:
  name: ai-components-service
spec:
  selector:
    app: ai-components
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: metrics
    port: 9090
    targetPort: metrics
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-components-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-components-monitor
spec:
  selector:
    matchLabels:
      app: ai-components
  endpoints:
  - port: metrics
    interval: 15s
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ai-components-network-policy
spec:
  podSelector:
    matchLabels:
      app: ai-components
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - podSelector:
        matchLabels:
          app: api-gateway
    ports:
    - protocol: TCP
      port: 3000
    - protocol: TCP
      port: 9090
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: vector-store
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 9090